[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "npm", "homebrew"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = true
# A GitHub repo to push Homebrew formulas to
tap = "cyfrin/homebrew-tap"
# A namespace to use when publishing this package to the npm registry
npm-scope = "@cyfrin"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "npm"]
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["ci"]

[dist.github-custom-runners]
global = "ubuntu-latest"
