[package]
name = "verifier"
version = "0.1.0"
edition = "2024"
default-run = "verifier"

[dependencies]
alloy.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
reqwest.workspace = true
tokio.workspace = true
safe-utils = { path = "../safe-utils"}
