[package]
name = "safe-utils"
version = "0.0.2"
edition = "2024"
publish = false

[dependencies]
semver.workspace = true
alloy.workspace = true
serde_json.workspace = true
target-triple = "0.1.4"
reqwest.workspace = true
dirs.workspace = true

[build-dependencies]
target-triple = "0.1.4"
